//// Generated by ProtoGen, Version=2.4.1.521, Culture=neutral, PublicKeyToken=55f7125234beb589.  DO NOT EDIT!
//#pragma warning disable 1591, 0612, 3021
//#region Designer generated code

//using pb = global::Google.ProtocolBuffers;
//using pbc = global::Google.ProtocolBuffers.Collections;
//using pbd = global::Google.ProtocolBuffers.Descriptors;
//using scg = global::System.Collections.Generic;
using ProtoBuf;
namespace com.tianhe.account.module.account.model
{

    //  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [ProtoContract]
    public class ChangeVo
    {

        //    #region Extension registration
        //    public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
        //    }
        //    #endregion
        //    #region Static variables
        //    internal static pbd::MessageDescriptor internal__static_com_tianhe_account_module_account_model_ChangeVo__Descriptor;
        //    internal static pb::FieldAccess.FieldAccessorTable<global::com.tianhe.account.module.account.model.ChangeVo, global::com.tianhe.account.module.account.model.ChangeVo.Builder> internal__static_com_tianhe_account_module_account_model_ChangeVo__FieldAccessorTable;
        //    internal static pbd::MessageDescriptor internal__static_com_tianhe_account_module_account_model_ChangeResult__Descriptor;
        //    internal static pb::FieldAccess.FieldAccessorTable<global::com.tianhe.account.module.account.model.ChangeResult, global::com.tianhe.account.module.account.model.ChangeResult.Builder> internal__static_com_tianhe_account_module_account_model_ChangeResult__FieldAccessorTable;
        //    #endregion
        //    #region Descriptor
        //    public static pbd::FileDescriptor Descriptor {
        //      get { return descriptor; }
        //    }
        //    private static pbd::FileDescriptor descriptor;

        //    static ChangeModel() {
        //      byte[] descriptorData = global::System.Convert.FromBase64String(
        //          "ChFDaGFuZ2VNb2RlbC5wcm90bxInY29tLnRpYW5oZS5hY2NvdW50Lm1vZHVs" + 
        //          "ZS5hY2NvdW50Lm1vZGVsIkcKCENoYW5nZVZvEgwKBG5hbWUYASACKAkSCwoD" + 
        //          "cHdkGAIgAigJEg4KBm5ld1B3ZBgDIAIoCRIQCghvcGVyYXRvchgEIAIoBSIc" + 
        //          "CgxDaGFuZ2VSZXN1bHQSDAoEY29kZRgBIAIoBQ==");
        //      pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
        //        descriptor = root;
        //        internal__static_com_tianhe_account_module_account_model_ChangeVo__Descriptor = Descriptor.MessageTypes[0];
        //        internal__static_com_tianhe_account_module_account_model_ChangeVo__FieldAccessorTable = 
        //            new pb::FieldAccess.FieldAccessorTable<global::com.tianhe.account.module.account.model.ChangeVo, global::com.tianhe.account.module.account.model.ChangeVo.Builder>(internal__static_com_tianhe_account_module_account_model_ChangeVo__Descriptor,
        //                new string[] { "Name", "Pwd", "NewPwd", "Operator", });
        //        internal__static_com_tianhe_account_module_account_model_ChangeResult__Descriptor = Descriptor.MessageTypes[1];
        //        internal__static_com_tianhe_account_module_account_model_ChangeResult__FieldAccessorTable = 
        //            new pb::FieldAccess.FieldAccessorTable<global::com.tianhe.account.module.account.model.ChangeResult, global::com.tianhe.account.module.account.model.ChangeResult.Builder>(internal__static_com_tianhe_account_module_account_model_ChangeResult__Descriptor,
        //                new string[] { "Code", });
        //        return null;
        //      };
        //      pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
        //          new pbd::FileDescriptor[] {
        //          }, assigner);
        //    }
        //    #endregion

        //  }
        //  #region Messages
        //  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        //  public sealed partial class ChangeVo : pb::GeneratedMessage<ChangeVo, ChangeVo.Builder> {
        //    private ChangeVo() { }
        //    private static readonly ChangeVo defaultInstance = new ChangeVo().MakeReadOnly();
        //    private static readonly string[] _changeVoFieldNames = new string[] { "name", "newPwd", "operator", "pwd" };
        //    private static readonly uint[] _changeVoFieldTags = new uint[] { 10, 26, 32, 18 };
        //    public static ChangeVo DefaultInstance {
        //      get { return defaultInstance; }
        //    }

        //    public override ChangeVo DefaultInstanceForType {
        //      get { return DefaultInstance; }
        //    }

        //    protected override ChangeVo ThisMessage {
        //      get { return this; }
        //    }

        //    public static pbd::MessageDescriptor Descriptor {
        //      get { return global::com.tianhe.account.module.account.model.ChangeModel.internal__static_com_tianhe_account_module_account_model_ChangeVo__Descriptor; }
        //    }

        //    protected override pb::FieldAccess.FieldAccessorTable<ChangeVo, ChangeVo.Builder> InternalFieldAccessors {
        //      get { return global::com.tianhe.account.module.account.model.ChangeModel.internal__static_com_tianhe_account_module_account_model_ChangeVo__FieldAccessorTable; }
        //    }

        //    public const int NameFieldNumber = 1;
        //    private bool hasName;
        //    private string name_ = "";
        //    public bool HasName {
        //      get { return hasName; }
        //    }
        //    public string Name {
        //      get { return name_; }
        //    }

        //    public const int PwdFieldNumber = 2;
        //    private bool hasPwd;
        //    private string pwd_ = "";
        //    public bool HasPwd {
        //      get { return hasPwd; }
        //    }
        //    public string Pwd {
        //      get { return pwd_; }
        //    }

        //    public const int NewPwdFieldNumber = 3;
        //    private bool hasNewPwd;
        //    private string newPwd_ = "";
        //    public bool HasNewPwd {
        //      get { return hasNewPwd; }
        //    }
        //    public string NewPwd {
        //      get { return newPwd_; }
        //    }

        //    public const int OperatorFieldNumber = 4;
        //    private bool hasOperator;
        //    private int operator_;
        //    public bool HasOperator {
        //      get { return hasOperator; }
        //    }
        //    public int Operator {
        //      get { return operator_; }
        //    }

        //    public override bool IsInitialized {
        //      get {
        //        if (!hasName) return false;
        //        if (!hasPwd) return false;
        //        if (!hasNewPwd) return false;
        //        if (!hasOperator) return false;
        //        return true;
        //      }
        //    }

        //    public override void WriteTo(pb::ICodedOutputStream output) {
        //      int size = SerializedSize;
        //      string[] field_names = _changeVoFieldNames;
        //      if (hasName) {
        //        output.WriteString(1, field_names[0], Name);
        //      }
        //      if (hasPwd) {
        //        output.WriteString(2, field_names[3], Pwd);
        //      }
        //      if (hasNewPwd) {
        //        output.WriteString(3, field_names[1], NewPwd);
        //      }
        //      if (hasOperator) {
        //        output.WriteInt32(4, field_names[2], Operator);
        //      }
        //      UnknownFields.WriteTo(output);
        //    }

        //    private int memoizedSerializedSize = -1;
        //    public override int SerializedSize {
        //      get {
        //        int size = memoizedSerializedSize;
        //        if (size != -1) return size;

        //        size = 0;
        //        if (hasName) {
        //          size += pb::CodedOutputStream.ComputeStringSize(1, Name);
        //        }
        //        if (hasPwd) {
        //          size += pb::CodedOutputStream.ComputeStringSize(2, Pwd);
        //        }
        //        if (hasNewPwd) {
        //          size += pb::CodedOutputStream.ComputeStringSize(3, NewPwd);
        //        }
        //        if (hasOperator) {
        //          size += pb::CodedOutputStream.ComputeInt32Size(4, Operator);
        //        }
        //        size += UnknownFields.SerializedSize;
        //        memoizedSerializedSize = size;
        //        return size;
        //      }
        //    }

        //    public static ChangeVo ParseFrom(pb::ByteString data) {
        //      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
        //    }
        //    public static ChangeVo ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
        //      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
        //    }
        //    public static ChangeVo ParseFrom(byte[] data) {
        //      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
        //    }
        //    public static ChangeVo ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
        //      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
        //    }
        //    public static ChangeVo ParseFrom(global::System.IO.Stream input) {
        //      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
        //    }
        //    public static ChangeVo ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
        //      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
        //    }
        //    public static ChangeVo ParseDelimitedFrom(global::System.IO.Stream input) {
        //      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
        //    }
        //    public static ChangeVo ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
        //      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
        //    }
        //    public static ChangeVo ParseFrom(pb::ICodedInputStream input) {
        //      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
        //    }
        //    public static ChangeVo ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        //      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
        //    }
        //    private ChangeVo MakeReadOnly() {
        //      return this;
        //    }

        //    public static Builder CreateBuilder() { return new Builder(); }
        //    public override Builder ToBuilder() { return CreateBuilder(this); }
        //    public override Builder CreateBuilderForType() { return new Builder(); }
        //    public static Builder CreateBuilder(ChangeVo prototype) {
        //      return new Builder(prototype);
        //    }

        //    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        //    public sealed partial class Builder : pb::GeneratedBuilder<ChangeVo, Builder> {
        //      protected override Builder ThisBuilder {
        //        get { return this; }
        //      }
        //      public Builder() {
        //        result = DefaultInstance;
        //        resultIsReadOnly = true;
        //      }
        //      internal Builder(ChangeVo cloneFrom) {
        //        result = cloneFrom;
        //        resultIsReadOnly = true;
        //      }

        //      private bool resultIsReadOnly;
        //      private ChangeVo result;

        //      private ChangeVo PrepareBuilder() {
        //        if (resultIsReadOnly) {
        //          ChangeVo original = result;
        //          result = new ChangeVo();
        //          resultIsReadOnly = false;
        //          MergeFrom(original);
        //        }
        //        return result;
        //      }

        //      public override bool IsInitialized {
        //        get { return result.IsInitialized; }
        //      }

        //      protected override ChangeVo MessageBeingBuilt {
        //        get { return PrepareBuilder(); }
        //      }

        //      public override Builder Clear() {
        //        result = DefaultInstance;
        //        resultIsReadOnly = true;
        //        return this;
        //      }

        //      public override Builder Clone() {
        //        if (resultIsReadOnly) {
        //          return new Builder(result);
        //        } else {
        //          return new Builder().MergeFrom(result);
        //        }
        //      }

        //      public override pbd::MessageDescriptor DescriptorForType {
        //        get { return global::com.tianhe.account.module.account.model.ChangeVo.Descriptor; }
        //      }

        //      public override ChangeVo DefaultInstanceForType {
        //        get { return global::com.tianhe.account.module.account.model.ChangeVo.DefaultInstance; }
        //      }

        //      public override ChangeVo BuildPartial() {
        //        if (resultIsReadOnly) {
        //          return result;
        //        }
        //        resultIsReadOnly = true;
        //        return result.MakeReadOnly();
        //      }

        //      public override Builder MergeFrom(pb::IMessage other) {
        //        if (other is ChangeVo) {
        //          return MergeFrom((ChangeVo) other);
        //        } else {
        //          base.MergeFrom(other);
        //          return this;
        //        }
        //      }

        //      public override Builder MergeFrom(ChangeVo other) {
        //        if (other == global::com.tianhe.account.module.account.model.ChangeVo.DefaultInstance) return this;
        //        PrepareBuilder();
        //        if (other.HasName) {
        //          Name = other.Name;
        //        }
        //        if (other.HasPwd) {
        //          Pwd = other.Pwd;
        //        }
        //        if (other.HasNewPwd) {
        //          NewPwd = other.NewPwd;
        //        }
        //        if (other.HasOperator) {
        //          Operator = other.Operator;
        //        }
        //        this.MergeUnknownFields(other.UnknownFields);
        //        return this;
        //      }

        //      public override Builder MergeFrom(pb::ICodedInputStream input) {
        //        return MergeFrom(input, pb::ExtensionRegistry.Empty);
        //      }

        //      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        //        PrepareBuilder();
        //        pb::UnknownFieldSet.Builder unknownFields = null;
        //        uint tag;
        //        string field_name;
        //        while (input.ReadTag(out tag, out field_name)) {
        //          if(tag == 0 && field_name != null) {
        //            int field_ordinal = global::System.Array.BinarySearch(_changeVoFieldNames, field_name, global::System.StringComparer.Ordinal);
        //            if(field_ordinal >= 0)
        //              tag = _changeVoFieldTags[field_ordinal];
        //            else {
        //              if (unknownFields == null) {
        //                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
        //              }
        //              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
        //              continue;
        //            }
        //          }
        //          switch (tag) {
        //            case 0: {
        //              throw pb::InvalidProtocolBufferException.InvalidTag();
        //            }
        //            default: {
        //              if (pb::WireFormat.IsEndGroupTag(tag)) {
        //                if (unknownFields != null) {
        //                  this.UnknownFields = unknownFields.Build();
        //                }
        //                return this;
        //              }
        //              if (unknownFields == null) {
        //                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
        //              }
        //              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
        //              break;
        //            }
        //            case 10: {
        //              result.hasName = input.ReadString(ref result.name_);
        //              break;
        //            }
        //            case 18: {
        //              result.hasPwd = input.ReadString(ref result.pwd_);
        //              break;
        //            }
        //            case 26: {
        //              result.hasNewPwd = input.ReadString(ref result.newPwd_);
        //              break;
        //            }
        //            case 32: {
        //              result.hasOperator = input.ReadInt32(ref result.operator_);
        //              break;
        //            }
        //          }
        //        }

        //        if (unknownFields != null) {
        //          this.UnknownFields = unknownFields.Build();
        //        }
        //        return this;
        //      }


        //      public bool HasName {
        //        get { return result.hasName; }
        //      }
        //      public string Name {
        //        get { return result.Name; }
        //        set { SetName(value); }
        //      }
        //      public Builder SetName(string value) {
        //        pb::ThrowHelper.ThrowIfNull(value, "value");
        //        PrepareBuilder();
        //        result.hasName = true;
        //        result.name_ = value;
        //        return this;
        //      }
        //      public Builder ClearName() {
        //        PrepareBuilder();
        //        result.hasName = false;
        //        result.name_ = "";
        //        return this;
        //      }

        //      public bool HasPwd {
        //        get { return result.hasPwd; }
        //      }
        //      public string Pwd {
        //        get { return result.Pwd; }
        //        set { SetPwd(value); }
        //      }
        //      public Builder SetPwd(string value) {
        //        pb::ThrowHelper.ThrowIfNull(value, "value");
        //        PrepareBuilder();
        //        result.hasPwd = true;
        //        result.pwd_ = value;
        //        return this;
        //      }
        //      public Builder ClearPwd() {
        //        PrepareBuilder();
        //        result.hasPwd = false;
        //        result.pwd_ = "";
        //        return this;
        //      }

        //      public bool HasNewPwd {
        //        get { return result.hasNewPwd; }
        //      }
        //      public string NewPwd {
        //        get { return result.NewPwd; }
        //        set { SetNewPwd(value); }
        //      }
        //      public Builder SetNewPwd(string value) {
        //        pb::ThrowHelper.ThrowIfNull(value, "value");
        //        PrepareBuilder();
        //        result.hasNewPwd = true;
        //        result.newPwd_ = value;
        //        return this;
        //      }
        //      public Builder ClearNewPwd() {
        //        PrepareBuilder();
        //        result.hasNewPwd = false;
        //        result.newPwd_ = "";
        //        return this;
        //      }

        //      public bool HasOperator {
        //        get { return result.hasOperator; }
        //      }
        //      public int Operator {
        //        get { return result.Operator; }
        //        set { SetOperator(value); }
        //      }
        //      public Builder SetOperator(int value) {
        //        PrepareBuilder();
        //        result.hasOperator = true;
        //        result.operator_ = value;
        //        return this;
        //      }
        //      public Builder ClearOperator() {
        //        PrepareBuilder();
        //        result.hasOperator = false;
        //        result.operator_ = 0;
        //        return this;
        //      }
        //    }
        //    static ChangeVo() {
        //      object.ReferenceEquals(global::com.tianhe.account.module.account.model.ChangeModel.Descriptor, null);
        //    }
        //  }

        //  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        //  public sealed partial class ChangeResult : pb::GeneratedMessage<ChangeResult, ChangeResult.Builder> {
        //    private ChangeResult() { }
        //    private static readonly ChangeResult defaultInstance = new ChangeResult().MakeReadOnly();
        //    private static readonly string[] _changeResultFieldNames = new string[] { "code" };
        //    private static readonly uint[] _changeResultFieldTags = new uint[] { 8 };
        //    public static ChangeResult DefaultInstance {
        //      get { return defaultInstance; }
        //    }

        //    public override ChangeResult DefaultInstanceForType {
        //      get { return DefaultInstance; }
        //    }

        //    protected override ChangeResult ThisMessage {
        //      get { return this; }
        //    }

        //    public static pbd::MessageDescriptor Descriptor {
        //      get { return global::com.tianhe.account.module.account.model.ChangeModel.internal__static_com_tianhe_account_module_account_model_ChangeResult__Descriptor; }
        //    }

        //    protected override pb::FieldAccess.FieldAccessorTable<ChangeResult, ChangeResult.Builder> InternalFieldAccessors {
        //      get { return global::com.tianhe.account.module.account.model.ChangeModel.internal__static_com_tianhe_account_module_account_model_ChangeResult__FieldAccessorTable; }
        //    }

        //    public const int CodeFieldNumber = 1;
        //    private bool hasCode;
        //    private int code_;
        //    public bool HasCode {
        //      get { return hasCode; }
        //    }
        //    public int Code {
        //      get { return code_; }
        //    }

        //    public override bool IsInitialized {
        //      get {
        //        if (!hasCode) return false;
        //        return true;
        //      }
        //    }

        //    public override void WriteTo(pb::ICodedOutputStream output) {
        //      int size = SerializedSize;
        //      string[] field_names = _changeResultFieldNames;
        //      if (hasCode) {
        //        output.WriteInt32(1, field_names[0], Code);
        //      }
        //      UnknownFields.WriteTo(output);
        //    }

        //    private int memoizedSerializedSize = -1;
        //    public override int SerializedSize {
        //      get {
        //        int size = memoizedSerializedSize;
        //        if (size != -1) return size;

        //        size = 0;
        //        if (hasCode) {
        //          size += pb::CodedOutputStream.ComputeInt32Size(1, Code);
        //        }
        //        size += UnknownFields.SerializedSize;
        //        memoizedSerializedSize = size;
        //        return size;
        //      }
        //    }

        //    public static ChangeResult ParseFrom(pb::ByteString data) {
        //      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
        //    }
        //    public static ChangeResult ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
        //      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
        //    }
        //    public static ChangeResult ParseFrom(byte[] data) {
        //      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
        //    }
        //    public static ChangeResult ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
        //      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
        //    }
        //    public static ChangeResult ParseFrom(global::System.IO.Stream input) {
        //      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
        //    }
        //    public static ChangeResult ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
        //      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
        //    }
        //    public static ChangeResult ParseDelimitedFrom(global::System.IO.Stream input) {
        //      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
        //    }
        //    public static ChangeResult ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
        //      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
        //    }
        //    public static ChangeResult ParseFrom(pb::ICodedInputStream input) {
        //      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
        //    }
        //    public static ChangeResult ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        //      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
        //    }
        //    private ChangeResult MakeReadOnly() {
        //      return this;
        //    }

        //    public static Builder CreateBuilder() { return new Builder(); }
        //    public override Builder ToBuilder() { return CreateBuilder(this); }
        //    public override Builder CreateBuilderForType() { return new Builder(); }
        //    public static Builder CreateBuilder(ChangeResult prototype) {
        //      return new Builder(prototype);
        //    }

        //    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        //    public sealed partial class Builder : pb::GeneratedBuilder<ChangeResult, Builder> {
        //      protected override Builder ThisBuilder {
        //        get { return this; }
        //      }
        //      public Builder() {
        //        result = DefaultInstance;
        //        resultIsReadOnly = true;
        //      }
        //      internal Builder(ChangeResult cloneFrom) {
        //        result = cloneFrom;
        //        resultIsReadOnly = true;
        //      }

        //      private bool resultIsReadOnly;
        //      private ChangeResult result;

        //      private ChangeResult PrepareBuilder() {
        //        if (resultIsReadOnly) {
        //          ChangeResult original = result;
        //          result = new ChangeResult();
        //          resultIsReadOnly = false;
        //          MergeFrom(original);
        //        }
        //        return result;
        //      }

        //      public override bool IsInitialized {
        //        get { return result.IsInitialized; }
        //      }

        //      protected override ChangeResult MessageBeingBuilt {
        //        get { return PrepareBuilder(); }
        //      }

        //      public override Builder Clear() {
        //        result = DefaultInstance;
        //        resultIsReadOnly = true;
        //        return this;
        //      }

        //      public override Builder Clone() {
        //        if (resultIsReadOnly) {
        //          return new Builder(result);
        //        } else {
        //          return new Builder().MergeFrom(result);
        //        }
        //      }

        //      public override pbd::MessageDescriptor DescriptorForType {
        //        get { return global::com.tianhe.account.module.account.model.ChangeResult.Descriptor; }
        //      }

        //      public override ChangeResult DefaultInstanceForType {
        //        get { return global::com.tianhe.account.module.account.model.ChangeResult.DefaultInstance; }
        //      }

        //      public override ChangeResult BuildPartial() {
        //        if (resultIsReadOnly) {
        //          return result;
        //        }
        //        resultIsReadOnly = true;
        //        return result.MakeReadOnly();
        //      }

        //      public override Builder MergeFrom(pb::IMessage other) {
        //        if (other is ChangeResult) {
        //          return MergeFrom((ChangeResult) other);
        //        } else {
        //          base.MergeFrom(other);
        //          return this;
        //        }
        //      }

        //      public override Builder MergeFrom(ChangeResult other) {
        //        if (other == global::com.tianhe.account.module.account.model.ChangeResult.DefaultInstance) return this;
        //        PrepareBuilder();
        //        if (other.HasCode) {
        //          Code = other.Code;
        //        }
        //        this.MergeUnknownFields(other.UnknownFields);
        //        return this;
        //      }

        //      public override Builder MergeFrom(pb::ICodedInputStream input) {
        //        return MergeFrom(input, pb::ExtensionRegistry.Empty);
        //      }

        //      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        //        PrepareBuilder();
        //        pb::UnknownFieldSet.Builder unknownFields = null;
        //        uint tag;
        //        string field_name;
        //        while (input.ReadTag(out tag, out field_name)) {
        //          if(tag == 0 && field_name != null) {
        //            int field_ordinal = global::System.Array.BinarySearch(_changeResultFieldNames, field_name, global::System.StringComparer.Ordinal);
        //            if(field_ordinal >= 0)
        //              tag = _changeResultFieldTags[field_ordinal];
        //            else {
        //              if (unknownFields == null) {
        //                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
        //              }
        //              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
        //              continue;
        //            }
        //          }
        //          switch (tag) {
        //            case 0: {
        //              throw pb::InvalidProtocolBufferException.InvalidTag();
        //            }
        //            default: {
        //              if (pb::WireFormat.IsEndGroupTag(tag)) {
        //                if (unknownFields != null) {
        //                  this.UnknownFields = unknownFields.Build();
        //                }
        //                return this;
        //              }
        //              if (unknownFields == null) {
        //                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
        //              }
        //              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
        //              break;
        //            }
        //            case 8: {
        //              result.hasCode = input.ReadInt32(ref result.code_);
        //              break;
        //            }
        //          }
        //        }

        //        if (unknownFields != null) {
        //          this.UnknownFields = unknownFields.Build();
        //        }
        //        return this;
        //      }


        //      public bool HasCode {
        //        get { return result.hasCode; }
        //      }
        //      public int Code {
        //        get { return result.Code; }
        //        set { SetCode(value); }
        //      }
        //      public Builder SetCode(int value) {
        //        PrepareBuilder();
        //        result.hasCode = true;
        //        result.code_ = value;
        //        return this;
        //      }
        //      public Builder ClearCode() {
        //        PrepareBuilder();
        //        result.hasCode = false;
        //        result.code_ = 0;
        //        return this;
        //      }
        //    }
        //    static ChangeResult() {
        //      object.ReferenceEquals(global::com.tianhe.account.module.account.model.ChangeModel.Descriptor, null);
        //    }
        /// <summary>
        /// ’ ∫≈√˚
        /// </summary>
        [ProtoMember(1)]
        string name;
        /// <summary>
        /// æ…√‹¬Î
        /// </summary>
        [ProtoMember(2)]
        string pwd;
        /// <summary>
        /// –¬√‹¬Î
        /// </summary>
        [ProtoMember(3)]
        string newPwd;
        /// <summary>
        /// ∆ΩÃ®∫≈
        /// </summary>
        [ProtoMember(4)]
        int operator_;
        public ChangeVo() { }
        public ChangeVo(string name, string pwd, string newPwd, int operator_)
        {
            this.name = name;
            this.pwd = pwd;
            this.newPwd = newPwd;
            this.operator_ = operator_;
        }
    }

    //  #endregion

}

//#endregion Designer generated code
