//// Generated by ProtoGen, Version=2.4.1.521, Culture=neutral, PublicKeyToken=55f7125234beb589.  DO NOT EDIT!
//#pragma warning disable 1591, 0612, 3021
//#region Designer generated code

//using pb = global::Google.ProtocolBuffers;
//using pbc = global::Google.ProtocolBuffers.Collections;
//using pbd = global::Google.ProtocolBuffers.Descriptors;
//using scg = global::System.Collections.Generic;
using ProtoBuf;
namespace com.tianhe.account.module.account.model
{

    //  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [ProtoContract]
    public class LoginVo
    {

        //    #region Extension registration
        //    public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
        //    }
        //    #endregion
        //    #region Static variables
        //    internal static pbd::MessageDescriptor internal__static_com_tianhe_account_module_account_model_LoginVo__Descriptor;
        //    internal static pb::FieldAccess.FieldAccessorTable<global::com.tianhe.account.module.account.model.LoginVo, global::com.tianhe.account.module.account.model.LoginVo.Builder> internal__static_com_tianhe_account_module_account_model_LoginVo__FieldAccessorTable;
        //    internal static pbd::MessageDescriptor internal__static_com_tianhe_account_module_account_model_LoginResult__Descriptor;
        //    internal static pb::FieldAccess.FieldAccessorTable<global::com.tianhe.account.module.account.model.LoginResult, global::com.tianhe.account.module.account.model.LoginResult.Builder> internal__static_com_tianhe_account_module_account_model_LoginResult__FieldAccessorTable;
        //    #endregion
        //    #region Descriptor
        //    public static pbd::FileDescriptor Descriptor {
        //      get { return descriptor; }
        //    }
        //    private static pbd::FileDescriptor descriptor;

        //    static LoginModel() {
        //      byte[] descriptorData = global::System.Convert.FromBase64String(
        //          "ChBMb2dpbk1vZGVsLnByb3RvEidjb20udGlhbmhlLmFjY291bnQubW9kdWxl" + 
        //          "LmFjY291bnQubW9kZWwiXQoHTG9naW5WbxIMCgRuYW1lGAEgAigJEhAKCHBh" + 
        //          "c3N3b3JkGAIgAigJEhAKCG9wZXJhdG9yGAMgAigFEhEKCXRpbWVzdGFtcBgE" + 
        //          "IAIoAxINCgV0b2tlbhgFIAEoCSJWCgtMb2dpblJlc3VsdBIMCgRjb2RlGAEg" + 
        //          "AigFEhAKCHNlcnZlcklkGAIgASgFEgoKAmlwGAMgASgJEgwKBHBvcnQYBCAB" + 
        //          "KAUSDQoFdG9rZW4YBSABKAk=");
        //      pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
        //        descriptor = root;
        //        internal__static_com_tianhe_account_module_account_model_LoginVo__Descriptor = Descriptor.MessageTypes[0];
        //        internal__static_com_tianhe_account_module_account_model_LoginVo__FieldAccessorTable = 
        //            new pb::FieldAccess.FieldAccessorTable<global::com.tianhe.account.module.account.model.LoginVo, global::com.tianhe.account.module.account.model.LoginVo.Builder>(internal__static_com_tianhe_account_module_account_model_LoginVo__Descriptor,
        //                new string[] { "Name", "Password", "Operator", "Timestamp", "Token", });
        //        internal__static_com_tianhe_account_module_account_model_LoginResult__Descriptor = Descriptor.MessageTypes[1];
        //        internal__static_com_tianhe_account_module_account_model_LoginResult__FieldAccessorTable = 
        //            new pb::FieldAccess.FieldAccessorTable<global::com.tianhe.account.module.account.model.LoginResult, global::com.tianhe.account.module.account.model.LoginResult.Builder>(internal__static_com_tianhe_account_module_account_model_LoginResult__Descriptor,
        //                new string[] { "Code", "ServerId", "Ip", "Port", "Token", });
        //        return null;
        //      };
        //      pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
        //          new pbd::FileDescriptor[] {
        //          }, assigner);
        //    }
        //    #endregion

        //  }
        //  #region Messages
        //  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        //  public sealed partial class LoginVo : pb::GeneratedMessage<LoginVo, LoginVo.Builder> {
        //    private LoginVo() { }
        //    private static readonly LoginVo defaultInstance = new LoginVo().MakeReadOnly();
        //    private static readonly string[] _loginVoFieldNames = new string[] { "name", "operator", "password", "timestamp", "token" };
        //    private static readonly uint[] _loginVoFieldTags = new uint[] { 10, 24, 18, 32, 42 };
        //    public static LoginVo DefaultInstance {
        //      get { return defaultInstance; }
        //    }

        //    public override LoginVo DefaultInstanceForType {
        //      get { return DefaultInstance; }
        //    }

        //    protected override LoginVo ThisMessage {
        //      get { return this; }
        //    }

        //    public static pbd::MessageDescriptor Descriptor {
        //      get { return global::com.tianhe.account.module.account.model.LoginModel.internal__static_com_tianhe_account_module_account_model_LoginVo__Descriptor; }
        //    }

        //    protected override pb::FieldAccess.FieldAccessorTable<LoginVo, LoginVo.Builder> InternalFieldAccessors {
        //      get { return global::com.tianhe.account.module.account.model.LoginModel.internal__static_com_tianhe_account_module_account_model_LoginVo__FieldAccessorTable; }
        //    }

        //    public const int NameFieldNumber = 1;
        //    private bool hasName;
        //    private string name_ = "";
        //    public bool HasName {
        //      get { return hasName; }
        //    }
        //    public string Name {
        //      get { return name_; }
        //    }

        //    public const int PasswordFieldNumber = 2;
        //    private bool hasPassword;
        //    private string password_ = "";
        //    public bool HasPassword {
        //      get { return hasPassword; }
        //    }
        //    public string Password {
        //      get { return password_; }
        //    }

        //    public const int OperatorFieldNumber = 3;
        //    private bool hasOperator;
        //    private int operator_;
        //    public bool HasOperator {
        //      get { return hasOperator; }
        //    }
        //    public int Operator {
        //      get { return operator_; }
        //    }

        //    public const int TimestampFieldNumber = 4;
        //    private bool hasTimestamp;
        //    private long timestamp_;
        //    public bool HasTimestamp {
        //      get { return hasTimestamp; }
        //    }
        //    public long Timestamp {
        //      get { return timestamp_; }
        //    }

        //    public const int TokenFieldNumber = 5;
        //    private bool hasToken;
        //    private string token_ = "";
        //    public bool HasToken {
        //      get { return hasToken; }
        //    }
        //    public string Token {
        //      get { return token_; }
        //    }

        //    public override bool IsInitialized {
        //      get {
        //        if (!hasName) return false;
        //        if (!hasPassword) return false;
        //        if (!hasOperator) return false;
        //        if (!hasTimestamp) return false;
        //        return true;
        //      }
        //    }

        //    public override void WriteTo(pb::ICodedOutputStream output) {
        //      int size = SerializedSize;
        //      string[] field_names = _loginVoFieldNames;
        //      if (hasName) {
        //        output.WriteString(1, field_names[0], Name);
        //      }
        //      if (hasPassword) {
        //        output.WriteString(2, field_names[2], Password);
        //      }
        //      if (hasOperator) {
        //        output.WriteInt32(3, field_names[1], Operator);
        //      }
        //      if (hasTimestamp) {
        //        output.WriteInt64(4, field_names[3], Timestamp);
        //      }
        //      if (hasToken) {
        //        output.WriteString(5, field_names[4], Token);
        //      }
        //      UnknownFields.WriteTo(output);
        //    }

        //    private int memoizedSerializedSize = -1;
        //    public override int SerializedSize {
        //      get {
        //        int size = memoizedSerializedSize;
        //        if (size != -1) return size;

        //        size = 0;
        //        if (hasName) {
        //          size += pb::CodedOutputStream.ComputeStringSize(1, Name);
        //        }
        //        if (hasPassword) {
        //          size += pb::CodedOutputStream.ComputeStringSize(2, Password);
        //        }
        //        if (hasOperator) {
        //          size += pb::CodedOutputStream.ComputeInt32Size(3, Operator);
        //        }
        //        if (hasTimestamp) {
        //          size += pb::CodedOutputStream.ComputeInt64Size(4, Timestamp);
        //        }
        //        if (hasToken) {
        //          size += pb::CodedOutputStream.ComputeStringSize(5, Token);
        //        }
        //        size += UnknownFields.SerializedSize;
        //        memoizedSerializedSize = size;
        //        return size;
        //      }
        //    }

        //    public static LoginVo ParseFrom(pb::ByteString data) {
        //      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
        //    }
        //    public static LoginVo ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
        //      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
        //    }
        //    public static LoginVo ParseFrom(byte[] data) {
        //      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
        //    }
        //    public static LoginVo ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
        //      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
        //    }
        //    public static LoginVo ParseFrom(global::System.IO.Stream input) {
        //      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
        //    }
        //    public static LoginVo ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
        //      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
        //    }
        //    public static LoginVo ParseDelimitedFrom(global::System.IO.Stream input) {
        //      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
        //    }
        //    public static LoginVo ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
        //      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
        //    }
        //    public static LoginVo ParseFrom(pb::ICodedInputStream input) {
        //      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
        //    }
        //    public static LoginVo ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        //      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
        //    }
        //    private LoginVo MakeReadOnly() {
        //      return this;
        //    }

        //    public static Builder CreateBuilder() { return new Builder(); }
        //    public override Builder ToBuilder() { return CreateBuilder(this); }
        //    public override Builder CreateBuilderForType() { return new Builder(); }
        //    public static Builder CreateBuilder(LoginVo prototype) {
        //      return new Builder(prototype);
        //    }

        //    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        //    public sealed partial class Builder : pb::GeneratedBuilder<LoginVo, Builder> {
        //      protected override Builder ThisBuilder {
        //        get { return this; }
        //      }
        //      public Builder() {
        //        result = DefaultInstance;
        //        resultIsReadOnly = true;
        //      }
        //      internal Builder(LoginVo cloneFrom) {
        //        result = cloneFrom;
        //        resultIsReadOnly = true;
        //      }

        //      private bool resultIsReadOnly;
        //      private LoginVo result;

        //      private LoginVo PrepareBuilder() {
        //        if (resultIsReadOnly) {
        //          LoginVo original = result;
        //          result = new LoginVo();
        //          resultIsReadOnly = false;
        //          MergeFrom(original);
        //        }
        //        return result;
        //      }

        //      public override bool IsInitialized {
        //        get { return result.IsInitialized; }
        //      }

        //      protected override LoginVo MessageBeingBuilt {
        //        get { return PrepareBuilder(); }
        //      }

        //      public override Builder Clear() {
        //        result = DefaultInstance;
        //        resultIsReadOnly = true;
        //        return this;
        //      }

        //      public override Builder Clone() {
        //        if (resultIsReadOnly) {
        //          return new Builder(result);
        //        } else {
        //          return new Builder().MergeFrom(result);
        //        }
        //      }

        //      public override pbd::MessageDescriptor DescriptorForType {
        //        get { return global::com.tianhe.account.module.account.model.LoginVo.Descriptor; }
        //      }

        //      public override LoginVo DefaultInstanceForType {
        //        get { return global::com.tianhe.account.module.account.model.LoginVo.DefaultInstance; }
        //      }

        //      public override LoginVo BuildPartial() {
        //        if (resultIsReadOnly) {
        //          return result;
        //        }
        //        resultIsReadOnly = true;
        //        return result.MakeReadOnly();
        //      }

        //      public override Builder MergeFrom(pb::IMessage other) {
        //        if (other is LoginVo) {
        //          return MergeFrom((LoginVo) other);
        //        } else {
        //          base.MergeFrom(other);
        //          return this;
        //        }
        //      }

        //      public override Builder MergeFrom(LoginVo other) {
        //        if (other == global::com.tianhe.account.module.account.model.LoginVo.DefaultInstance) return this;
        //        PrepareBuilder();
        //        if (other.HasName) {
        //          Name = other.Name;
        //        }
        //        if (other.HasPassword) {
        //          Password = other.Password;
        //        }
        //        if (other.HasOperator) {
        //          Operator = other.Operator;
        //        }
        //        if (other.HasTimestamp) {
        //          Timestamp = other.Timestamp;
        //        }
        //        if (other.HasToken) {
        //          Token = other.Token;
        //        }
        //        this.MergeUnknownFields(other.UnknownFields);
        //        return this;
        //      }

        //      public override Builder MergeFrom(pb::ICodedInputStream input) {
        //        return MergeFrom(input, pb::ExtensionRegistry.Empty);
        //      }

        //      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        //        PrepareBuilder();
        //        pb::UnknownFieldSet.Builder unknownFields = null;
        //        uint tag;
        //        string field_name;
        //        while (input.ReadTag(out tag, out field_name)) {
        //          if(tag == 0 && field_name != null) {
        //            int field_ordinal = global::System.Array.BinarySearch(_loginVoFieldNames, field_name, global::System.StringComparer.Ordinal);
        //            if(field_ordinal >= 0)
        //              tag = _loginVoFieldTags[field_ordinal];
        //            else {
        //              if (unknownFields == null) {
        //                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
        //              }
        //              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
        //              continue;
        //            }
        //          }
        //          switch (tag) {
        //            case 0: {
        //              throw pb::InvalidProtocolBufferException.InvalidTag();
        //            }
        //            default: {
        //              if (pb::WireFormat.IsEndGroupTag(tag)) {
        //                if (unknownFields != null) {
        //                  this.UnknownFields = unknownFields.Build();
        //                }
        //                return this;
        //              }
        //              if (unknownFields == null) {
        //                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
        //              }
        //              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
        //              break;
        //            }
        //            case 10: {
        //              result.hasName = input.ReadString(ref result.name_);
        //              break;
        //            }
        //            case 18: {
        //              result.hasPassword = input.ReadString(ref result.password_);
        //              break;
        //            }
        //            case 24: {
        //              result.hasOperator = input.ReadInt32(ref result.operator_);
        //              break;
        //            }
        //            case 32: {
        //              result.hasTimestamp = input.ReadInt64(ref result.timestamp_);
        //              break;
        //            }
        //            case 42: {
        //              result.hasToken = input.ReadString(ref result.token_);
        //              break;
        //            }
        //          }
        //        }

        //        if (unknownFields != null) {
        //          this.UnknownFields = unknownFields.Build();
        //        }
        //        return this;
        //      }


        //      public bool HasName {
        //        get { return result.hasName; }
        //      }
        //      public string Name {
        //        get { return result.Name; }
        //        set { SetName(value); }
        //      }
        //      public Builder SetName(string value) {
        //        pb::ThrowHelper.ThrowIfNull(value, "value");
        //        PrepareBuilder();
        //        result.hasName = true;
        //        result.name_ = value;
        //        return this;
        //      }
        //      public Builder ClearName() {
        //        PrepareBuilder();
        //        result.hasName = false;
        //        result.name_ = "";
        //        return this;
        //      }

        //      public bool HasPassword {
        //        get { return result.hasPassword; }
        //      }
        //      public string Password {
        //        get { return result.Password; }
        //        set { SetPassword(value); }
        //      }
        //      public Builder SetPassword(string value) {
        //        pb::ThrowHelper.ThrowIfNull(value, "value");
        //        PrepareBuilder();
        //        result.hasPassword = true;
        //        result.password_ = value;
        //        return this;
        //      }
        //      public Builder ClearPassword() {
        //        PrepareBuilder();
        //        result.hasPassword = false;
        //        result.password_ = "";
        //        return this;
        //      }

        //      public bool HasOperator {
        //        get { return result.hasOperator; }
        //      }
        //      public int Operator {
        //        get { return result.Operator; }
        //        set { SetOperator(value); }
        //      }
        //      public Builder SetOperator(int value) {
        //        PrepareBuilder();
        //        result.hasOperator = true;
        //        result.operator_ = value;
        //        return this;
        //      }
        //      public Builder ClearOperator() {
        //        PrepareBuilder();
        //        result.hasOperator = false;
        //        result.operator_ = 0;
        //        return this;
        //      }

        //      public bool HasTimestamp {
        //        get { return result.hasTimestamp; }
        //      }
        //      public long Timestamp {
        //        get { return result.Timestamp; }
        //        set { SetTimestamp(value); }
        //      }
        //      public Builder SetTimestamp(long value) {
        //        PrepareBuilder();
        //        result.hasTimestamp = true;
        //        result.timestamp_ = value;
        //        return this;
        //      }
        //      public Builder ClearTimestamp() {
        //        PrepareBuilder();
        //        result.hasTimestamp = false;
        //        result.timestamp_ = 0L;
        //        return this;
        //      }

        //      public bool HasToken {
        //        get { return result.hasToken; }
        //      }
        //      public string Token {
        //        get { return result.Token; }
        //        set { SetToken(value); }
        //      }
        //      public Builder SetToken(string value) {
        //        pb::ThrowHelper.ThrowIfNull(value, "value");
        //        PrepareBuilder();
        //        result.hasToken = true;
        //        result.token_ = value;
        //        return this;
        //      }
        //      public Builder ClearToken() {
        //        PrepareBuilder();
        //        result.hasToken = false;
        //        result.token_ = "";
        //        return this;
        //      }
        //    }
        //    static LoginVo() {
        //      object.ReferenceEquals(global::com.tianhe.account.module.account.model.LoginModel.Descriptor, null);
        //    }
        //  }

        //  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        //  public sealed partial class LoginResult : pb::GeneratedMessage<LoginResult, LoginResult.Builder> {
        //    private LoginResult() { }
        //    private static readonly LoginResult defaultInstance = new LoginResult().MakeReadOnly();
        //    private static readonly string[] _loginResultFieldNames = new string[] { "code", "ip", "port", "serverId", "token" };
        //    private static readonly uint[] _loginResultFieldTags = new uint[] { 8, 26, 32, 16, 42 };
        //    public static LoginResult DefaultInstance {
        //      get { return defaultInstance; }
        //    }

        //    public override LoginResult DefaultInstanceForType {
        //      get { return DefaultInstance; }
        //    }

        //    protected override LoginResult ThisMessage {
        //      get { return this; }
        //    }

        //    public static pbd::MessageDescriptor Descriptor {
        //      get { return global::com.tianhe.account.module.account.model.LoginModel.internal__static_com_tianhe_account_module_account_model_LoginResult__Descriptor; }
        //    }

        //    protected override pb::FieldAccess.FieldAccessorTable<LoginResult, LoginResult.Builder> InternalFieldAccessors {
        //      get { return global::com.tianhe.account.module.account.model.LoginModel.internal__static_com_tianhe_account_module_account_model_LoginResult__FieldAccessorTable; }
        //    }

        //    public const int CodeFieldNumber = 1;
        //    private bool hasCode;
        //    private int code_;
        //    public bool HasCode {
        //      get { return hasCode; }
        //    }
        //    public int Code {
        //      get { return code_; }
        //    }

        //    public const int ServerIdFieldNumber = 2;
        //    private bool hasServerId;
        //    private int serverId_;
        //    public bool HasServerId {
        //      get { return hasServerId; }
        //    }
        //    public int ServerId {
        //      get { return serverId_; }
        //    }

        //    public const int IpFieldNumber = 3;
        //    private bool hasIp;
        //    private string ip_ = "";
        //    public bool HasIp {
        //      get { return hasIp; }
        //    }
        //    public string Ip {
        //      get { return ip_; }
        //    }

        //    public const int PortFieldNumber = 4;
        //    private bool hasPort;
        //    private int port_;
        //    public bool HasPort {
        //      get { return hasPort; }
        //    }
        //    public int Port {
        //      get { return port_; }
        //    }

        //    public const int TokenFieldNumber = 5;
        //    private bool hasToken;
        //    private string token_ = "";
        //    public bool HasToken {
        //      get { return hasToken; }
        //    }
        //    public string Token {
        //      get { return token_; }
        //    }

        //    public override bool IsInitialized {
        //      get {
        //        if (!hasCode) return false;
        //        return true;
        //      }
        //    }

        //    public override void WriteTo(pb::ICodedOutputStream output) {
        //      int size = SerializedSize;
        //      string[] field_names = _loginResultFieldNames;
        //      if (hasCode) {
        //        output.WriteInt32(1, field_names[0], Code);
        //      }
        //      if (hasServerId) {
        //        output.WriteInt32(2, field_names[3], ServerId);
        //      }
        //      if (hasIp) {
        //        output.WriteString(3, field_names[1], Ip);
        //      }
        //      if (hasPort) {
        //        output.WriteInt32(4, field_names[2], Port);
        //      }
        //      if (hasToken) {
        //        output.WriteString(5, field_names[4], Token);
        //      }
        //      UnknownFields.WriteTo(output);
        //    }

        //    private int memoizedSerializedSize = -1;
        //    public override int SerializedSize {
        //      get {
        //        int size = memoizedSerializedSize;
        //        if (size != -1) return size;

        //        size = 0;
        //        if (hasCode) {
        //          size += pb::CodedOutputStream.ComputeInt32Size(1, Code);
        //        }
        //        if (hasServerId) {
        //          size += pb::CodedOutputStream.ComputeInt32Size(2, ServerId);
        //        }
        //        if (hasIp) {
        //          size += pb::CodedOutputStream.ComputeStringSize(3, Ip);
        //        }
        //        if (hasPort) {
        //          size += pb::CodedOutputStream.ComputeInt32Size(4, Port);
        //        }
        //        if (hasToken) {
        //          size += pb::CodedOutputStream.ComputeStringSize(5, Token);
        //        }
        //        size += UnknownFields.SerializedSize;
        //        memoizedSerializedSize = size;
        //        return size;
        //      }
        //    }

        //    public static LoginResult ParseFrom(pb::ByteString data) {
        //      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
        //    }
        //    public static LoginResult ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
        //      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
        //    }
        //    public static LoginResult ParseFrom(byte[] data) {
        //      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
        //    }
        //    public static LoginResult ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
        //      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
        //    }
        //    public static LoginResult ParseFrom(global::System.IO.Stream input) {
        //      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
        //    }
        //    public static LoginResult ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
        //      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
        //    }
        //    public static LoginResult ParseDelimitedFrom(global::System.IO.Stream input) {
        //      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
        //    }
        //    public static LoginResult ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
        //      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
        //    }
        //    public static LoginResult ParseFrom(pb::ICodedInputStream input) {
        //      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
        //    }
        //    public static LoginResult ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        //      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
        //    }
        //    private LoginResult MakeReadOnly() {
        //      return this;
        //    }

        //    public static Builder CreateBuilder() { return new Builder(); }
        //    public override Builder ToBuilder() { return CreateBuilder(this); }
        //    public override Builder CreateBuilderForType() { return new Builder(); }
        //    public static Builder CreateBuilder(LoginResult prototype) {
        //      return new Builder(prototype);
        //    }

        //    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        //    public sealed partial class Builder : pb::GeneratedBuilder<LoginResult, Builder> {
        //      protected override Builder ThisBuilder {
        //        get { return this; }
        //      }
        //      public Builder() {
        //        result = DefaultInstance;
        //        resultIsReadOnly = true;
        //      }
        //      internal Builder(LoginResult cloneFrom) {
        //        result = cloneFrom;
        //        resultIsReadOnly = true;
        //      }

        //      private bool resultIsReadOnly;
        //      private LoginResult result;

        //      private LoginResult PrepareBuilder() {
        //        if (resultIsReadOnly) {
        //          LoginResult original = result;
        //          result = new LoginResult();
        //          resultIsReadOnly = false;
        //          MergeFrom(original);
        //        }
        //        return result;
        //      }

        //      public override bool IsInitialized {
        //        get { return result.IsInitialized; }
        //      }

        //      protected override LoginResult MessageBeingBuilt {
        //        get { return PrepareBuilder(); }
        //      }

        //      public override Builder Clear() {
        //        result = DefaultInstance;
        //        resultIsReadOnly = true;
        //        return this;
        //      }

        //      public override Builder Clone() {
        //        if (resultIsReadOnly) {
        //          return new Builder(result);
        //        } else {
        //          return new Builder().MergeFrom(result);
        //        }
        //      }

        //      public override pbd::MessageDescriptor DescriptorForType {
        //        get { return global::com.tianhe.account.module.account.model.LoginResult.Descriptor; }
        //      }

        //      public override LoginResult DefaultInstanceForType {
        //        get { return global::com.tianhe.account.module.account.model.LoginResult.DefaultInstance; }
        //      }

        //      public override LoginResult BuildPartial() {
        //        if (resultIsReadOnly) {
        //          return result;
        //        }
        //        resultIsReadOnly = true;
        //        return result.MakeReadOnly();
        //      }

        //      public override Builder MergeFrom(pb::IMessage other) {
        //        if (other is LoginResult) {
        //          return MergeFrom((LoginResult) other);
        //        } else {
        //          base.MergeFrom(other);
        //          return this;
        //        }
        //      }

        //      public override Builder MergeFrom(LoginResult other) {
        //        if (other == global::com.tianhe.account.module.account.model.LoginResult.DefaultInstance) return this;
        //        PrepareBuilder();
        //        if (other.HasCode) {
        //          Code = other.Code;
        //        }
        //        if (other.HasServerId) {
        //          ServerId = other.ServerId;
        //        }
        //        if (other.HasIp) {
        //          Ip = other.Ip;
        //        }
        //        if (other.HasPort) {
        //          Port = other.Port;
        //        }
        //        if (other.HasToken) {
        //          Token = other.Token;
        //        }
        //        this.MergeUnknownFields(other.UnknownFields);
        //        return this;
        //      }

        //      public override Builder MergeFrom(pb::ICodedInputStream input) {
        //        return MergeFrom(input, pb::ExtensionRegistry.Empty);
        //      }

        //      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        //        PrepareBuilder();
        //        pb::UnknownFieldSet.Builder unknownFields = null;
        //        uint tag;
        //        string field_name;
        //        while (input.ReadTag(out tag, out field_name)) {
        //          if(tag == 0 && field_name != null) {
        //            int field_ordinal = global::System.Array.BinarySearch(_loginResultFieldNames, field_name, global::System.StringComparer.Ordinal);
        //            if(field_ordinal >= 0)
        //              tag = _loginResultFieldTags[field_ordinal];
        //            else {
        //              if (unknownFields == null) {
        //                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
        //              }
        //              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
        //              continue;
        //            }
        //          }
        //          switch (tag) {
        //            case 0: {
        //              throw pb::InvalidProtocolBufferException.InvalidTag();
        //            }
        //            default: {
        //              if (pb::WireFormat.IsEndGroupTag(tag)) {
        //                if (unknownFields != null) {
        //                  this.UnknownFields = unknownFields.Build();
        //                }
        //                return this;
        //              }
        //              if (unknownFields == null) {
        //                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
        //              }
        //              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
        //              break;
        //            }
        //            case 8: {
        //              result.hasCode = input.ReadInt32(ref result.code_);
        //              break;
        //            }
        //            case 16: {
        //              result.hasServerId = input.ReadInt32(ref result.serverId_);
        //              break;
        //            }
        //            case 26: {
        //              result.hasIp = input.ReadString(ref result.ip_);
        //              break;
        //            }
        //            case 32: {
        //              result.hasPort = input.ReadInt32(ref result.port_);
        //              break;
        //            }
        //            case 42: {
        //              result.hasToken = input.ReadString(ref result.token_);
        //              break;
        //            }
        //          }
        //        }

        //        if (unknownFields != null) {
        //          this.UnknownFields = unknownFields.Build();
        //        }
        //        return this;
        //      }


        //      public bool HasCode {
        //        get { return result.hasCode; }
        //      }
        //      public int Code {
        //        get { return result.Code; }
        //        set { SetCode(value); }
        //      }
        //      public Builder SetCode(int value) {
        //        PrepareBuilder();
        //        result.hasCode = true;
        //        result.code_ = value;
        //        return this;
        //      }
        //      public Builder ClearCode() {
        //        PrepareBuilder();
        //        result.hasCode = false;
        //        result.code_ = 0;
        //        return this;
        //      }

        //      public bool HasServerId {
        //        get { return result.hasServerId; }
        //      }
        //      public int ServerId {
        //        get { return result.ServerId; }
        //        set { SetServerId(value); }
        //      }
        //      public Builder SetServerId(int value) {
        //        PrepareBuilder();
        //        result.hasServerId = true;
        //        result.serverId_ = value;
        //        return this;
        //      }
        //      public Builder ClearServerId() {
        //        PrepareBuilder();
        //        result.hasServerId = false;
        //        result.serverId_ = 0;
        //        return this;
        //      }

        //      public bool HasIp {
        //        get { return result.hasIp; }
        //      }
        //      public string Ip {
        //        get { return result.Ip; }
        //        set { SetIp(value); }
        //      }
        //      public Builder SetIp(string value) {
        //        pb::ThrowHelper.ThrowIfNull(value, "value");
        //        PrepareBuilder();
        //        result.hasIp = true;
        //        result.ip_ = value;
        //        return this;
        //      }
        //      public Builder ClearIp() {
        //        PrepareBuilder();
        //        result.hasIp = false;
        //        result.ip_ = "";
        //        return this;
        //      }

        //      public bool HasPort {
        //        get { return result.hasPort; }
        //      }
        //      public int Port {
        //        get { return result.Port; }
        //        set { SetPort(value); }
        //      }
        //      public Builder SetPort(int value) {
        //        PrepareBuilder();
        //        result.hasPort = true;
        //        result.port_ = value;
        //        return this;
        //      }
        //      public Builder ClearPort() {
        //        PrepareBuilder();
        //        result.hasPort = false;
        //        result.port_ = 0;
        //        return this;
        //      }

        //      public bool HasToken {
        //        get { return result.hasToken; }
        //      }
        //      public string Token {
        //        get { return result.Token; }
        //        set { SetToken(value); }
        //      }
        //      public Builder SetToken(string value) {
        //        pb::ThrowHelper.ThrowIfNull(value, "value");
        //        PrepareBuilder();
        //        result.hasToken = true;
        //        result.token_ = value;
        //        return this;
        //      }
        //      public Builder ClearToken() {
        //        PrepareBuilder();
        //        result.hasToken = false;
        //        result.token_ = "";
        //        return this;
        //      }
        //    }
        //    static LoginResult() {
        //      object.ReferenceEquals(global::com.tianhe.account.module.account.model.LoginModel.Descriptor, null);
        //    }
        /// <summary>
        /// 帐号
        /// </summary>
        [ProtoMember(1)]
        string name;
        /// <summary>
        /// 密码
        /// </summary>
        [ProtoMember(2)]
        string password;
        /// <summary>
        /// 平台号
        /// </summary>
        [ProtoMember(3)]
        int operator_;
        /// <summary>
        /// 服务器时间戳
        /// </summary>
        [ProtoMember(4)]
        long timestamp;
        /// <summary>
        /// 登录token
        /// </summary>
        [ProtoMember(5)]
        string token;

        public LoginVo() { }
        public LoginVo(string name, string password, int operator_, long timestamp, string token)
        {
            this.name = name;
            this.password = password;
            this.operator_ = operator_;
            this.timestamp = timestamp;
            this.token = token;
        }
    }

    //  #endregion

}

//#endregion Designer generated code
